/* Generated by wayland-scanner 1.23.1 */

/*
 * SPDX-FileCopyrightText: 2026 CharOfString <root@charofstring.cc>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface gxde_screenshot_frame_v1_interface;

static const struct wl_interface *gxde_screenshot_v1_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&gxde_screenshot_frame_v1_interface,
	NULL,
	NULL,
	&gxde_screenshot_frame_v1_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&gxde_screenshot_frame_v1_interface,
	NULL,
	NULL,
	&gxde_screenshot_frame_v1_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
};

static const struct wl_message gxde_screenshot_manager_v1_requests[] = {
	{ "capture_output", "nsu", gxde_screenshot_v1_types + 9 },
	{ "capture_output_region", "nsiiuuu", gxde_screenshot_v1_types + 12 },
	{ "capture_window", "nsu", gxde_screenshot_v1_types + 19 },
	{ "capture_window_thumbnail", "nssuuu", gxde_screenshot_v1_types + 22 },
	{ "destroy", "", gxde_screenshot_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface gxde_screenshot_manager_v1_interface = {
	"gxde_screenshot_manager_v1", 1,
	5, gxde_screenshot_manager_v1_requests,
	0, NULL,
};

static const struct wl_message gxde_screenshot_frame_v1_requests[] = {
	{ "destroy", "", gxde_screenshot_v1_types + 0 },
	{ "release_buffer", "u", gxde_screenshot_v1_types + 0 },
};

static const struct wl_message gxde_screenshot_frame_v1_events[] = {
	{ "failed", "", gxde_screenshot_v1_types + 0 },
	{ "cancelled", "", gxde_screenshot_v1_types + 0 },
	{ "buffer", "huuuuuuuu", gxde_screenshot_v1_types + 0 },
	{ "buffer_with_plane", "uhuu", gxde_screenshot_v1_types + 0 },
	{ "buffer_done", "", gxde_screenshot_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface gxde_screenshot_frame_v1_interface = {
	"gxde_screenshot_frame_v1", 1,
	2, gxde_screenshot_frame_v1_requests,
	5, gxde_screenshot_frame_v1_events,
};

