/* Generated by wayland-scanner 1.23.1 */

#ifndef GXDE_SCREENSHOT_V1_CLIENT_PROTOCOL_H
#define GXDE_SCREENSHOT_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_gxde_screenshot_v1 The gxde_screenshot_v1 protocol
 * GXDE screenshot protocol
 *
 * @section page_desc_gxde_screenshot_v1 Description
 *
 * Simple protocol to capture screen/window.
 *
 * @section page_ifaces_gxde_screenshot_v1 Interfaces
 * - @subpage page_iface_gxde_screenshot_manager_v1 - screenshot request manager
 * - @subpage page_iface_gxde_screenshot_frame_v1 - captured frame
 * @section page_copyright_gxde_screenshot_v1 Copyright
 * <pre>
 *
 * SPDX-FileCopyrightText: 2026 CharOfString <root@charofstring.cc>
 * SPDX-License-Identifier: GPL-3.0-or-later
 * </pre>
 */
struct gxde_screenshot_frame_v1;
struct gxde_screenshot_manager_v1;

#ifndef GXDE_SCREENSHOT_MANAGER_V1_INTERFACE
#define GXDE_SCREENSHOT_MANAGER_V1_INTERFACE
/**
 * @page page_iface_gxde_screenshot_manager_v1 gxde_screenshot_manager_v1
 * @section page_iface_gxde_screenshot_manager_v1_desc Description
 *
 * The manager creates frame objects for screenshot and window preview
 * requests.
 * @section page_iface_gxde_screenshot_manager_v1_api API
 * See @ref iface_gxde_screenshot_manager_v1.
 */
/**
 * @defgroup iface_gxde_screenshot_manager_v1 The gxde_screenshot_manager_v1 interface
 *
 * The manager creates frame objects for screenshot and window preview
 * requests.
 */
extern const struct wl_interface gxde_screenshot_manager_v1_interface;
#endif
#ifndef GXDE_SCREENSHOT_FRAME_V1_INTERFACE
#define GXDE_SCREENSHOT_FRAME_V1_INTERFACE
/**
 * @page page_iface_gxde_screenshot_frame_v1 gxde_screenshot_frame_v1
 * @section page_iface_gxde_screenshot_frame_v1_desc Description
 *
 * A frame object receives buffer metadata when capture succeeds.
 * @section page_iface_gxde_screenshot_frame_v1_api API
 * See @ref iface_gxde_screenshot_frame_v1.
 */
/**
 * @defgroup iface_gxde_screenshot_frame_v1 The gxde_screenshot_frame_v1 interface
 *
 * A frame object receives buffer metadata when capture succeeds.
 */
extern const struct wl_interface gxde_screenshot_frame_v1_interface;
#endif

#define GXDE_SCREENSHOT_MANAGER_V1_CAPTURE_OUTPUT 0
#define GXDE_SCREENSHOT_MANAGER_V1_CAPTURE_OUTPUT_REGION 1
#define GXDE_SCREENSHOT_MANAGER_V1_CAPTURE_WINDOW 2
#define GXDE_SCREENSHOT_MANAGER_V1_CAPTURE_WINDOW_THUMBNAIL 3
#define GXDE_SCREENSHOT_MANAGER_V1_DESTROY 4


/**
 * @ingroup iface_gxde_screenshot_manager_v1
 */
#define GXDE_SCREENSHOT_MANAGER_V1_CAPTURE_OUTPUT_SINCE_VERSION 1
/**
 * @ingroup iface_gxde_screenshot_manager_v1
 */
#define GXDE_SCREENSHOT_MANAGER_V1_CAPTURE_OUTPUT_REGION_SINCE_VERSION 1
/**
 * @ingroup iface_gxde_screenshot_manager_v1
 */
#define GXDE_SCREENSHOT_MANAGER_V1_CAPTURE_WINDOW_SINCE_VERSION 1
/**
 * @ingroup iface_gxde_screenshot_manager_v1
 */
#define GXDE_SCREENSHOT_MANAGER_V1_CAPTURE_WINDOW_THUMBNAIL_SINCE_VERSION 1
/**
 * @ingroup iface_gxde_screenshot_manager_v1
 */
#define GXDE_SCREENSHOT_MANAGER_V1_DESTROY_SINCE_VERSION 1

/** @ingroup iface_gxde_screenshot_manager_v1 */
static inline void
gxde_screenshot_manager_v1_set_user_data(struct gxde_screenshot_manager_v1 *gxde_screenshot_manager_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) gxde_screenshot_manager_v1, user_data);
}

/** @ingroup iface_gxde_screenshot_manager_v1 */
static inline void *
gxde_screenshot_manager_v1_get_user_data(struct gxde_screenshot_manager_v1 *gxde_screenshot_manager_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) gxde_screenshot_manager_v1);
}

static inline uint32_t
gxde_screenshot_manager_v1_get_version(struct gxde_screenshot_manager_v1 *gxde_screenshot_manager_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) gxde_screenshot_manager_v1);
}

/**
 * @ingroup iface_gxde_screenshot_manager_v1
 *
 * Capture one frame of the specified output.
 */
static inline struct gxde_screenshot_frame_v1 *
gxde_screenshot_manager_v1_capture_output(struct gxde_screenshot_manager_v1 *gxde_screenshot_manager_v1, const char *output, uint32_t overlay_cursor)
{
	struct wl_proxy *frame;

	frame = wl_proxy_marshal_flags((struct wl_proxy *) gxde_screenshot_manager_v1,
			 GXDE_SCREENSHOT_MANAGER_V1_CAPTURE_OUTPUT, &gxde_screenshot_frame_v1_interface, wl_proxy_get_version((struct wl_proxy *) gxde_screenshot_manager_v1), 0, NULL, output, overlay_cursor);

	return (struct gxde_screenshot_frame_v1 *) frame;
}

/**
 * @ingroup iface_gxde_screenshot_manager_v1
 *
 * Capture one frame of a region in the specified output. The x and y
 * coordinates anchored TOP LEFT.
 */
static inline struct gxde_screenshot_frame_v1 *
gxde_screenshot_manager_v1_capture_output_region(struct gxde_screenshot_manager_v1 *gxde_screenshot_manager_v1, const char *output, int32_t x, int32_t y, uint32_t width, uint32_t height, uint32_t overlay_cursor)
{
	struct wl_proxy *frame;

	frame = wl_proxy_marshal_flags((struct wl_proxy *) gxde_screenshot_manager_v1,
			 GXDE_SCREENSHOT_MANAGER_V1_CAPTURE_OUTPUT_REGION, &gxde_screenshot_frame_v1_interface, wl_proxy_get_version((struct wl_proxy *) gxde_screenshot_manager_v1), 0, NULL, output, x, y, width, height, overlay_cursor);

	return (struct gxde_screenshot_frame_v1 *) frame;
}

/**
 * @ingroup iface_gxde_screenshot_manager_v1
 *
 * Capture one frame of the specified window (IDENTIFY WINDOW BY UUID).
 */
static inline struct gxde_screenshot_frame_v1 *
gxde_screenshot_manager_v1_capture_window(struct gxde_screenshot_manager_v1 *gxde_screenshot_manager_v1, const char *window, uint32_t without_decoration)
{
	struct wl_proxy *frame;

	frame = wl_proxy_marshal_flags((struct wl_proxy *) gxde_screenshot_manager_v1,
			 GXDE_SCREENSHOT_MANAGER_V1_CAPTURE_WINDOW, &gxde_screenshot_frame_v1_interface, wl_proxy_get_version((struct wl_proxy *) gxde_screenshot_manager_v1), 0, NULL, window, without_decoration);

	return (struct gxde_screenshot_frame_v1 *) frame;
}

/**
 * @ingroup iface_gxde_screenshot_manager_v1
 *
 * Capture a scaled preview of the specified window (IDENTIFY WINDOW BY UUID).
 * If app_id is provided, then we can return all thumbnails of windows of that app,
 * which is useful for task switcher, task bar, and docks.\
 * It is FINE if app_id is empty, then we will only grab the thumbnail for single window.
 */
static inline struct gxde_screenshot_frame_v1 *
gxde_screenshot_manager_v1_capture_window_thumbnail(struct gxde_screenshot_manager_v1 *gxde_screenshot_manager_v1, const char *app_id, const char *window, uint32_t max_width, uint32_t max_height, uint32_t without_decoration)
{
	struct wl_proxy *frame;

	frame = wl_proxy_marshal_flags((struct wl_proxy *) gxde_screenshot_manager_v1,
			 GXDE_SCREENSHOT_MANAGER_V1_CAPTURE_WINDOW_THUMBNAIL, &gxde_screenshot_frame_v1_interface, wl_proxy_get_version((struct wl_proxy *) gxde_screenshot_manager_v1), 0, NULL, app_id, window, max_width, max_height, without_decoration);

	return (struct gxde_screenshot_frame_v1 *) frame;
}

/**
 * @ingroup iface_gxde_screenshot_manager_v1
 *
 * Destroy this manager object.
 * Be careful, frame objects will also be destoryed.
 */
static inline void
gxde_screenshot_manager_v1_destroy(struct gxde_screenshot_manager_v1 *gxde_screenshot_manager_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) gxde_screenshot_manager_v1,
			 GXDE_SCREENSHOT_MANAGER_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) gxde_screenshot_manager_v1), WL_MARSHAL_FLAG_DESTROY);
}

#ifndef GXDE_SCREENSHOT_FRAME_V1_FLAGS_ENUM
#define GXDE_SCREENSHOT_FRAME_V1_FLAGS_ENUM
enum gxde_screenshot_frame_v1_flags {
	/**
	 * buffer is a dmabuf
	 */
	GXDE_SCREENSHOT_FRAME_V1_FLAGS_DMABUF = 1,
	/**
	 * buffer is reused
	 */
	GXDE_SCREENSHOT_FRAME_V1_FLAGS_REUSED = 2,
};
#endif /* GXDE_SCREENSHOT_FRAME_V1_FLAGS_ENUM */

/**
 * @ingroup iface_gxde_screenshot_frame_v1
 * @struct gxde_screenshot_frame_v1_listener
 */
struct gxde_screenshot_frame_v1_listener {
	/**
	 * capture failed
	 *
	 * The capture request failed, the client should destroy the
	 * frame object.
	 */
	void (*failed)(void *data,
		       struct gxde_screenshot_frame_v1 *gxde_screenshot_frame_v1);
	/**
	 * source cancelled
	 *
	 * The source was destroyed or became unavailable. Remember to
	 * destory the frame object.
	 */
	void (*cancelled)(void *data,
			  struct gxde_screenshot_frame_v1 *gxde_screenshot_frame_v1);
	/**
	 * buffer information
	 *
	 * Provides buffer parameters for the first plane of this frame.
	 * @param fd buffer file descriptor
	 * @param format DRM_FORMAT code
	 * @param width buffer width in pixels
	 * @param height buffer height in pixels
	 * @param offset buffer offset in bytes
	 * @param stride buffer stride in bytes
	 * @param modifier_hi high 32 bits of layout modifier
	 * @param modifier_lo low 32 bits of layout modifier
	 * @param flags buffer flags
	 */
	void (*buffer)(void *data,
		       struct gxde_screenshot_frame_v1 *gxde_screenshot_frame_v1,
		       int32_t fd,
		       uint32_t format,
		       uint32_t width,
		       uint32_t height,
		       uint32_t offset,
		       uint32_t stride,
		       uint32_t modifier_hi,
		       uint32_t modifier_lo,
		       uint32_t flags);
	/**
	 * additional plane information
	 *
	 * Provides fd, offset, and stride for planes after the first
	 * one.
	 * @param index plane index
	 * @param fd buffer file descriptor
	 * @param offset buffer offset in bytes
	 * @param stride buffer stride in bytes
	 */
	void (*buffer_with_plane)(void *data,
				  struct gxde_screenshot_frame_v1 *gxde_screenshot_frame_v1,
				  uint32_t index,
				  int32_t fd,
				  uint32_t offset,
				  uint32_t stride);
	/**
	 * all buffer parameters have been sent
	 *
	 * Sent after buffer and all buffer_with_plane events.
	 */
	void (*buffer_done)(void *data,
			    struct gxde_screenshot_frame_v1 *gxde_screenshot_frame_v1);
};

/**
 * @ingroup iface_gxde_screenshot_frame_v1
 */
static inline int
gxde_screenshot_frame_v1_add_listener(struct gxde_screenshot_frame_v1 *gxde_screenshot_frame_v1,
				      const struct gxde_screenshot_frame_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) gxde_screenshot_frame_v1,
				     (void (**)(void)) listener, data);
}

#define GXDE_SCREENSHOT_FRAME_V1_DESTROY 0
#define GXDE_SCREENSHOT_FRAME_V1_RELEASE_BUFFER 1

/**
 * @ingroup iface_gxde_screenshot_frame_v1
 */
#define GXDE_SCREENSHOT_FRAME_V1_FAILED_SINCE_VERSION 1
/**
 * @ingroup iface_gxde_screenshot_frame_v1
 */
#define GXDE_SCREENSHOT_FRAME_V1_CANCELLED_SINCE_VERSION 1
/**
 * @ingroup iface_gxde_screenshot_frame_v1
 */
#define GXDE_SCREENSHOT_FRAME_V1_BUFFER_SINCE_VERSION 1
/**
 * @ingroup iface_gxde_screenshot_frame_v1
 */
#define GXDE_SCREENSHOT_FRAME_V1_BUFFER_WITH_PLANE_SINCE_VERSION 1
/**
 * @ingroup iface_gxde_screenshot_frame_v1
 */
#define GXDE_SCREENSHOT_FRAME_V1_BUFFER_DONE_SINCE_VERSION 1

/**
 * @ingroup iface_gxde_screenshot_frame_v1
 */
#define GXDE_SCREENSHOT_FRAME_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_gxde_screenshot_frame_v1
 */
#define GXDE_SCREENSHOT_FRAME_V1_RELEASE_BUFFER_SINCE_VERSION 1

/** @ingroup iface_gxde_screenshot_frame_v1 */
static inline void
gxde_screenshot_frame_v1_set_user_data(struct gxde_screenshot_frame_v1 *gxde_screenshot_frame_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) gxde_screenshot_frame_v1, user_data);
}

/** @ingroup iface_gxde_screenshot_frame_v1 */
static inline void *
gxde_screenshot_frame_v1_get_user_data(struct gxde_screenshot_frame_v1 *gxde_screenshot_frame_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) gxde_screenshot_frame_v1);
}

static inline uint32_t
gxde_screenshot_frame_v1_get_version(struct gxde_screenshot_frame_v1 *gxde_screenshot_frame_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) gxde_screenshot_frame_v1);
}

/**
 * @ingroup iface_gxde_screenshot_frame_v1
 *
 * Destroy this frame object.
 */
static inline void
gxde_screenshot_frame_v1_destroy(struct gxde_screenshot_frame_v1 *gxde_screenshot_frame_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) gxde_screenshot_frame_v1,
			 GXDE_SCREENSHOT_FRAME_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) gxde_screenshot_frame_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_gxde_screenshot_frame_v1
 *
 * Notify WM that the client no longer reads the last buffer.
 * If want_buffer is non-zero, the compositor may send a new buffer event
 * when the source content changes.
 */
static inline void
gxde_screenshot_frame_v1_release_buffer(struct gxde_screenshot_frame_v1 *gxde_screenshot_frame_v1, uint32_t want_buffer)
{
	wl_proxy_marshal_flags((struct wl_proxy *) gxde_screenshot_frame_v1,
			 GXDE_SCREENSHOT_FRAME_V1_RELEASE_BUFFER, NULL, wl_proxy_get_version((struct wl_proxy *) gxde_screenshot_frame_v1), 0, want_buffer);
}

#ifdef  __cplusplus
}
#endif

#endif
