/* Generated by wayland-scanner 1.23.1 */

/*
 * SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
 * SPDX-FileCopyrightText: 2024 Hongfei Shang
 *
 * SPDX-License-Identifier: MulanPSL-2.0
 *
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface org_ukui_activation_interface;
extern const struct wl_interface ukui_window_interface;
extern const struct wl_interface wl_output_interface;
extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *ukui_window_management_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	&ukui_window_interface,
	NULL,
	&wl_surface_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	&wl_surface_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	&wl_surface_interface,
	&wl_output_interface,
	&ukui_window_interface,
	&org_ukui_activation_interface,
};

static const struct wl_message ukui_window_management_requests[] = {
	{ "show_desktop", "u", ukui_window_management_types + 0 },
	{ "create_window", "ns", ukui_window_management_types + 4 },
};

static const struct wl_message ukui_window_management_events[] = {
	{ "show_desktop_changed", "u", ukui_window_management_types + 0 },
	{ "stacking_order_changed", "s", ukui_window_management_types + 0 },
	{ "window_created", "s", ukui_window_management_types + 0 },
};

WL_PRIVATE const struct wl_interface ukui_window_management_interface = {
	"ukui_window_management", 1,
	2, ukui_window_management_requests,
	3, ukui_window_management_events,
};

static const struct wl_message ukui_window_requests[] = {
	{ "set_state", "uu", ukui_window_management_types + 0 },
	{ "set_startup_geometry", "ouuuu", ukui_window_management_types + 6 },
	{ "set_minimized_geometry", "ouuuu", ukui_window_management_types + 11 },
	{ "unset_minimized_geometry", "o", ukui_window_management_types + 16 },
	{ "close", "", ukui_window_management_types + 0 },
	{ "request_move", "", ukui_window_management_types + 0 },
	{ "request_resize", "", ukui_window_management_types + 0 },
	{ "destroy", "", ukui_window_management_types + 0 },
	{ "get_icon", "h", ukui_window_management_types + 0 },
	{ "request_enter_virtual_desktop", "s", ukui_window_management_types + 0 },
	{ "request_enter_new_virtual_desktop", "", ukui_window_management_types + 0 },
	{ "request_leave_virtual_desktop", "s", ukui_window_management_types + 0 },
	{ "request_enter_activity", "s", ukui_window_management_types + 0 },
	{ "request_leave_activity", "s", ukui_window_management_types + 0 },
	{ "send_to_output", "o", ukui_window_management_types + 17 },
	{ "highlight", "", ukui_window_management_types + 0 },
	{ "unset_highlight", "", ukui_window_management_types + 0 },
};

static const struct wl_message ukui_window_events[] = {
	{ "title_changed", "s", ukui_window_management_types + 0 },
	{ "app_id_changed", "s", ukui_window_management_types + 0 },
	{ "state_changed", "u", ukui_window_management_types + 0 },
	{ "themed_icon_name_changed", "s", ukui_window_management_types + 0 },
	{ "unmapped", "", ukui_window_management_types + 0 },
	{ "initial_state", "", ukui_window_management_types + 0 },
	{ "parent_window", "?o", ukui_window_management_types + 18 },
	{ "geometry", "iiuu", ukui_window_management_types + 0 },
	{ "icon_changed", "", ukui_window_management_types + 0 },
	{ "pid_changed", "u", ukui_window_management_types + 0 },
	{ "virtual_desktop_entered", "s", ukui_window_management_types + 0 },
	{ "virtual_desktop_left", "s", ukui_window_management_types + 0 },
	{ "application_menu", "ss", ukui_window_management_types + 0 },
	{ "activity_entered", "s", ukui_window_management_types + 0 },
	{ "activity_left", "s", ukui_window_management_types + 0 },
	{ "resource_name_changed", "s", ukui_window_management_types + 0 },
};

WL_PRIVATE const struct wl_interface ukui_window_interface = {
	"ukui_window", 1,
	17, ukui_window_requests,
	16, ukui_window_events,
};

static const struct wl_message org_ukui_activation_feedback_requests[] = {
	{ "destroy", "", ukui_window_management_types + 0 },
};

static const struct wl_message org_ukui_activation_feedback_events[] = {
	{ "activation", "n", ukui_window_management_types + 19 },
};

WL_PRIVATE const struct wl_interface org_ukui_activation_feedback_interface = {
	"org_ukui_activation_feedback", 1,
	1, org_ukui_activation_feedback_requests,
	1, org_ukui_activation_feedback_events,
};

static const struct wl_message org_ukui_activation_requests[] = {
	{ "destroy", "", ukui_window_management_types + 0 },
};

static const struct wl_message org_ukui_activation_events[] = {
	{ "app_id", "s", ukui_window_management_types + 0 },
	{ "finished", "", ukui_window_management_types + 0 },
};

WL_PRIVATE const struct wl_interface org_ukui_activation_interface = {
	"org_ukui_activation", 1,
	1, org_ukui_activation_requests,
	2, org_ukui_activation_events,
};

