# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
# SPDX-License-Identifier: MulanPSL-2.0

from .kywc_toplevel_manager_v1 import KywcToplevelManagerV1  # noqa: F401
from .kywc_toplevel_v1 import KywcToplevelV1  # noqa: F401
