# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
# SPDX-License-Identifier: MulanPSL-2.0

from __future__ import annotations

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from .kywc_toplevel_v1 import KywcToplevelV1


class KywcToplevelManagerV1(Interface):
    """List and control toplevels

    A toplevel is defined as a surface with a role similar to xdg_toplevel.
    XWayland surfaces may be treated like toplevels in this protocol.

    After a client binds the global, each mapped toplevel window will be sent
    using the toplevel event.
    """

    name = "kywc_toplevel_manager_v1"
    version = 1


class KywcToplevelManagerV1Proxy(Proxy[KywcToplevelManagerV1]):
    interface = KywcToplevelManagerV1

    @KywcToplevelManagerV1.request()
    def stop(self) -> None:
        """Stop sending events

        This request indicates that the client no longer wishes to receive
        events for new toplevels.

        The Wayland protocol is asynchronous, meaning the compositor may send
        further toplevel events until the stop request is processed. The client
        should wait for a finished event before destroying this object.
        """
        self._marshal(0)


class KywcToplevelManagerV1Resource(Resource):
    interface = KywcToplevelManagerV1

    @KywcToplevelManagerV1.event(
        Argument(ArgumentType.NewId, interface=KywcToplevelV1),
        Argument(ArgumentType.String),
    )
    def toplevel(self, toplevel: KywcToplevelV1, uuid: str) -> None:
        """A toplevel has been created

        This event is emitted whenever a new toplevel window is created. It is
        emitted for all toplevels, regardless of the app that has created them.

        All initial properties of the toplevel (identifier, title, app_id) will
        be sent immediately after this event using the corresponding events for
        kywc_toplevel. The compositor will use the done event to indicate when
        all data has been sent.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.kywc_toplevel_v1.KywcToplevelV1`
        :param uuid:
            unique id of the toplevel
        :type uuid:
            `ArgumentType.String`
        """
        self._post_event(0, toplevel, uuid)

    @KywcToplevelManagerV1.event()
    def finished(self) -> None:
        """The compositor has finished with the toplevel manager

        This event indicates that the compositor is done sending events to this
        object. The client should destroy the object. See destroy for more
        information.

        The compositor must not send any more toplevel events after this event.
        """
        self._post_event(1)


class KywcToplevelManagerV1Global(Global):
    interface = KywcToplevelManagerV1


KywcToplevelManagerV1._gen_c()
KywcToplevelManagerV1.proxy_class = KywcToplevelManagerV1Proxy
KywcToplevelManagerV1.resource_class = KywcToplevelManagerV1Resource
KywcToplevelManagerV1.global_class = KywcToplevelManagerV1Global
