# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
# SPDX-License-Identifier: MulanPSL-2.0

from __future__ import annotations

import enum

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)


class KywcToplevelV1(Interface):
    """A mapped toplevel

    A :class:`KywcToplevelV1` object represents a mapped toplevel window. A
    single app may have multiple mapped toplevels.
    """

    name = "kywc_toplevel_v1"
    version = 1

    class capability(enum.IntFlag):
        skip_taskbar = 1
        skip_switcher = 2

    class state(enum.IntFlag):
        maximized = 1
        minimized = 2
        activated = 4
        fullscreen = 8


class KywcToplevelV1Proxy(Proxy[KywcToplevelV1]):
    interface = KywcToplevelV1

    @KywcToplevelV1.request()
    def destroy(self) -> None:
        """Destroy the object

        This request should be used when the client will no longer use the
        toplevel  or after the closed event has been received to allow
        destruction of the object.
        """
        self._marshal(0)
        self._destroy()

    @KywcToplevelV1.request(
        Argument(ArgumentType.String, nullable=True),
    )
    def set_maximized(self, output: str | None) -> None:
        """Requests that the toplevel be maximized

        Requests that the toplevel be maximized. If the maximized state
        actually changes, this will be indicated by the state event.

        :param output:
            the output unique id
        :type output:
            `ArgumentType.String` or `None`
        """
        self._marshal(1, output)

    @KywcToplevelV1.request()
    def unset_maximized(self) -> None:
        """Requests that the toplevel be unmaximized

        Requests that the toplevel be unmaximized. If the maximized state
        actually changes, this will be indicated by the state event.
        """
        self._marshal(2)

    @KywcToplevelV1.request()
    def set_minimized(self) -> None:
        """Requests that the toplevel be minimized

        Requests that the toplevel be minimized. If the minimized state
        actually changes, this will be indicated by the state event.
        """
        self._marshal(3)

    @KywcToplevelV1.request()
    def unset_minimized(self) -> None:
        """Requests that the toplevel be unminimized

        Requests that the toplevel be unminimized. If the minimized state
        actually changes, this will be indicated by the state event.
        """
        self._marshal(4)

    @KywcToplevelV1.request(
        Argument(ArgumentType.String, nullable=True),
    )
    def set_fullscreen(self, output: str | None) -> None:
        """Request that the toplevel be fullscreened

        Requests that the toplevel be fullscreened on the given output. If the
        fullscreen state and/or the outputs the toplevel is visible on actually
        change, this will be indicated by the state and output_enter/leave
        events.

        The output parameter is only a hint to the compositor. Also, if output
        is NULL, the compositor should decide which output the toplevel will be
        fullscreened on, if at all.

        :param output:
            the output unique id
        :type output:
            `ArgumentType.String` or `None`
        """
        self._marshal(5, output)

    @KywcToplevelV1.request()
    def unset_fullscreen(self) -> None:
        """Request that the toplevel be unfullscreened

        Requests that the toplevel be unfullscreened. If the fullscreen state
        actually changes, this will be indicated by the state event.
        """
        self._marshal(6)

    @KywcToplevelV1.request()
    def activate(self) -> None:
        """Activate the toplevel

        Request that this toplevel be activated. There is no guarantee the
        toplevel will be actually activated.
        """
        self._marshal(7)

    @KywcToplevelV1.request()
    def close(self) -> None:
        """Request that the toplevel be closed

        Send a request to the toplevel to close itself. The compositor would
        typically use a shell-specific method to carry out this request, for
        example by sending the xdg_toplevel.close event. However, this gives no
        guarantees the toplevel will actually be destroyed. If and when this
        happens, the closed event will be emitted.
        """
        self._marshal(8)

    @KywcToplevelV1.request(
        Argument(ArgumentType.String),
    )
    def enter_workspace(self, id: str) -> None:
        """Map window on a workspace

        Make the toplevel enter a workspace. A toplevel can enter more than one
        workspace. if the id is empty or invalid, no action will be performed.

        :param id:
            the workspace unique id
        :type id:
            `ArgumentType.String`
        """
        self._marshal(9, id)

    @KywcToplevelV1.request(
        Argument(ArgumentType.String),
    )
    def leave_workspace(self, id: str) -> None:
        """Remove a toplevel from a workspace

        Make the toplevel exit a workspace.

        :param id:
            the workspace unique id
        :type id:
            `ArgumentType.String`
        """
        self._marshal(10, id)

    @KywcToplevelV1.request(
        Argument(ArgumentType.String),
    )
    def move_to_workspace(self, id: str) -> None:
        """Move toplevel to specified workspace

        Requests this toplevel to be displayed only in a specific workspace.

        :param id:
            the workspace unique id
        :type id:
            `ArgumentType.String`
        """
        self._marshal(11, id)

    @KywcToplevelV1.request(
        Argument(ArgumentType.String),
    )
    def move_to_output(self, id: str) -> None:
        """Move toplevel to specified output

        Requests this toplevel to be displayed in a specific output.

        :param id:
            the output unique id
        :type id:
            `ArgumentType.String`
        """
        self._marshal(12, id)

    @KywcToplevelV1.request(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def set_position(self, x: int, y: int) -> None:
        """Change the window position

        Move the window to new coordinates.

        :param x:
            x coordinate in global space
        :type x:
            `ArgumentType.Int`
        :param y:
            y coordinate in global space
        :type y:
            `ArgumentType.Int`
        """
        self._marshal(13, x, y)

    @KywcToplevelV1.request(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def set_size(self, width: int, height: int) -> None:
        """Change the window size

        Set the window to new size.

        Window size will be consider compositor window size limits.

        :param width:
        :type width:
            `ArgumentType.Uint`
        :param height:
        :type height:
            `ArgumentType.Uint`
        """
        self._marshal(14, width, height)


class KywcToplevelV1Resource(Resource):
    interface = KywcToplevelV1

    @KywcToplevelV1.event()
    def closed(self) -> None:
        """The toplevel has been closed

        The server will emit no further events on the :class:`KywcToplevelV1`
        after this event. Any requests received aside from the destroy request
        must be ignored. Upon receiving this event, the client should destroy
        the handle.
        """
        self._post_event(0)

    @KywcToplevelV1.event()
    def done(self) -> None:
        """All information about the toplevel has been sent

        This event is sent after all changes in the toplevel state have been
        sent.
        """
        self._post_event(1)

    @KywcToplevelV1.event(
        Argument(ArgumentType.String),
    )
    def title(self, title: str) -> None:
        """Title change

        The title of the toplevel has changed.

        :param title:
        :type title:
            `ArgumentType.String`
        """
        self._post_event(2, title)

    @KywcToplevelV1.event(
        Argument(ArgumentType.String),
    )
    def app_id(self, app_id: str) -> None:
        """App_id change

        The app id of the topleve.done for details.

        :param app_id:
        :type app_id:
            `ArgumentType.String`
        """
        self._post_event(3, app_id)

    @KywcToplevelV1.event(
        Argument(ArgumentType.String),
    )
    def primary_output(self, output: str) -> None:
        """Toplevel's primary output changes

        This event is emitted whenever the output that the largest area of this
        toplevel is displayed on has changed.

        :param output:
            the output unique id
        :type output:
            `ArgumentType.String`
        """
        self._post_event(4, output)

    @KywcToplevelV1.event(
        Argument(ArgumentType.String),
    )
    def workspace_enter(self, workspace: str) -> None:
        """Toplevel entered a workspace

        This event is emitted whenever the toplevel becomes visible on the
        given workspace. A toplevel may be visible on multiple workspaces.

        :param workspace:
            the workspace unique id
        :type workspace:
            `ArgumentType.String`
        """
        self._post_event(5, workspace)

    @KywcToplevelV1.event(
        Argument(ArgumentType.String),
    )
    def workspace_leave(self, workspace: str) -> None:
        """Toplevel left a workspace

        This event is emitted whenever the toplevel stops being visible on the
        given workspace. It is guaranteed that an entered-workspace event with
        the same workspace has been emitted before this event.

        :param workspace:
            the workspace unique id
        :type workspace:
            `ArgumentType.String`
        """
        self._post_event(6, workspace)

    @KywcToplevelV1.event(
        Argument(ArgumentType.Uint),
    )
    def capabilities(self, flags: int) -> None:
        """Capability flags

        What capabilities this toplevel has, sent on startup before the first
        done event.

        :param flags:
        :type flags:
            `ArgumentType.Uint`
        """
        self._post_event(7, flags)

    @KywcToplevelV1.event(
        Argument(ArgumentType.Uint),
    )
    def state(self, state: int) -> None:
        """The toplevel state changed

        This event is emitted immediately after the :class:`KywcToplevelV1`  is
        created and each time the toplevel state changes, either because of a
        compositor action or because of a request in this protocol.

        :param state:
        :type state:
            `ArgumentType.Uint`
        """
        self._post_event(8, state)

    @KywcToplevelV1.event(
        Argument(ArgumentType.Object, interface=KywcToplevelV1, nullable=True),
    )
    def parent(self, parent: KywcToplevelV1 | None) -> None:
        """Parent change

        This event is emitted whenever the parent of the toplevel changes.

        No event is emitted when the parent handle is destroyed by the client.

        :param parent:
        :type parent:
            :class:`KywcToplevelV1` or `None`
        """
        self._post_event(9, parent)

    @KywcToplevelV1.event(
        Argument(ArgumentType.String),
    )
    def icon(self, name: str) -> None:
        """Toplevel's icon changed

        This event will be sent whenever the icon changes. May be null.

        :param name:
            the new icon name
        :type name:
            `ArgumentType.String`
        """
        self._post_event(10, name)

    @KywcToplevelV1.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def geometry(self, x: int, y: int, width: int, height: int) -> None:
        """The geometry of this toplevel in absolute coordinates

        This event will be sent whenever the toplevel geometry changes.

        :param x:
            x position of the toplevel
        :type x:
            `ArgumentType.Int`
        :param y:
            y position of the toplevel
        :type y:
            `ArgumentType.Int`
        :param width:
            width of the toplevel
        :type width:
            `ArgumentType.Uint`
        :param height:
            height of the toplevel
        :type height:
            `ArgumentType.Uint`
        """
        self._post_event(11, x, y, width, height)

    @KywcToplevelV1.event(
        Argument(ArgumentType.Uint),
    )
    def pid(self, pid: int) -> None:
        """Process id of application owning the window

        This event will only be emitted once, before the first "done" event
        occurs.

        :param pid:
            process id
        :type pid:
            `ArgumentType.Uint`
        """
        self._post_event(12, pid)


class KywcToplevelV1Global(Global):
    interface = KywcToplevelV1


KywcToplevelV1._gen_c()
KywcToplevelV1.proxy_class = KywcToplevelV1Proxy
KywcToplevelV1.resource_class = KywcToplevelV1Resource
KywcToplevelV1.global_class = KywcToplevelV1Global
