# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
# SPDX-License-Identifier: MulanPSL-2.0

from .kywc_workspace_manager_v1 import KywcWorkspaceManagerV1  # noqa: F401
from .kywc_workspace_v1 import KywcWorkspaceV1  # noqa: F401
