# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
# SPDX-License-Identifier: MulanPSL-2.0

from __future__ import annotations

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from .kywc_workspace_v1 import KywcWorkspaceV1


class KywcWorkspaceManagerV1(Interface):
    """List and control workspaces

    Workspaces, also called virtual desktops, are groups of surfaces. A
    compositor with a concept of workspaces may only show some such groups of
    surfaces (those of 'active' workspaces) at a time. 'Activating' a workspace
    is a request for the compositor to display that workspace's surfaces as
    normal, whereas the compositor may hide or otherwise de-emphasise surfaces
    that are associated only with 'inactive' workspaces.

    After a client binds the :class:`KywcWorkspaceManagerV1`, each workspace
    will be sent via the workspace event.
    """

    name = "kywc_workspace_manager_v1"
    version = 1


class KywcWorkspaceManagerV1Proxy(Proxy[KywcWorkspaceManagerV1]):
    interface = KywcWorkspaceManagerV1

    @KywcWorkspaceManagerV1.request(
        Argument(ArgumentType.String, nullable=True),
        Argument(ArgumentType.Uint),
    )
    def create_workspace(self, name: str | None, position: int) -> None:
        """Create a new workspace

        Request that the compositor create a new workspace with the given name
        and position it at a specified position.

        If the position is zero or less, it will be positioned at the
        beginning, if the position is the count or more, it will be positioned
        at the end.

        There is no guarantee that the compositor will create a new workspace,
        or that the created workspace will have the provided name and position.

        :param name:
            the user readable name we want
        :type name:
            `ArgumentType.String` or `None`
        :param position:
            the position we want for the workspace
        :type position:
            `ArgumentType.Uint`
        """
        self._marshal(0, name, position)

    @KywcWorkspaceManagerV1.request()
    def stop(self) -> None:
        """Stop sending events

        Indicates the client no longer wishes to receive events for new
        workspace. However the compositor may emit further workspace events,
        until the finished event is emitted. The compositor is expected to send
        the finished event eventually once the stop request has been processed.

        The client must not send any more requests after this one.
        """
        self._marshal(1)


class KywcWorkspaceManagerV1Resource(Resource):
    interface = KywcWorkspaceManagerV1

    @KywcWorkspaceManagerV1.event(
        Argument(ArgumentType.NewId, interface=KywcWorkspaceV1),
        Argument(ArgumentType.String),
    )
    def workspace(self, workspace: KywcWorkspaceV1, uuid: str) -> None:
        """Workspace has been created

        This event is emitted whenever a new workspace has been created.

        All initial details of the workspace (name, position, activated) will
        be sent immediately after this event via the corresponding events in
        :class:`~pywayland.protocol.kywc_workspace_v1.KywcWorkspaceV1`.

        :param workspace:
        :type workspace:
            :class:`~pywayland.protocol.kywc_workspace_v1.KywcWorkspaceV1`
        :param uuid:
            Unique id of the workspace
        :type uuid:
            `ArgumentType.String`
        """
        self._post_event(0, workspace, uuid)

    @KywcWorkspaceManagerV1.event()
    def done(self) -> None:
        """All information about the workspaces has been sent

        This event is sent after all changes in all workspaces have been sent.

        This allows changes to one or more
        :class:`~pywayland.protocol.kywc_workspace_v1.KywcWorkspaceV1`
        properties to be seen as atomic, even if they happen via multiple
        events.
        """
        self._post_event(1)

    @KywcWorkspaceManagerV1.event()
    def finished(self) -> None:
        """The compositor has finished with the workspace_manager

        This event indicates that the compositor is done sending events to the
        :class:`KywcWorkspaceManagerV1`. The server will destroy the object
        immediately after sending this request, so it will become invalid and
        the client should free any resources associated with it.
        """
        self._post_event(2)


class KywcWorkspaceManagerV1Global(Global):
    interface = KywcWorkspaceManagerV1


KywcWorkspaceManagerV1._gen_c()
KywcWorkspaceManagerV1.proxy_class = KywcWorkspaceManagerV1Proxy
KywcWorkspaceManagerV1.resource_class = KywcWorkspaceManagerV1Resource
KywcWorkspaceManagerV1.global_class = KywcWorkspaceManagerV1Global
