# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
# SPDX-License-Identifier: MulanPSL-2.0

from __future__ import annotations

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)


class KywcWorkspaceV1(Interface):
    """A workspace handing a group of surfaces

    A :class:`KywcWorkspaceV1` object represents a workspace that handles a
    group of surfaces.

    Each workspace has a name, conveyed to the client with the name event; and
    a position, conveyed to the client with the position event. The client may
    request that the compositor activate or deactivate the workspace.
    """

    name = "kywc_workspace_v1"
    version = 1


class KywcWorkspaceV1Proxy(Proxy[KywcWorkspaceV1]):
    interface = KywcWorkspaceV1

    @KywcWorkspaceV1.request()
    def destroy(self) -> None:
        """Destroy the :class:`KywcWorkspaceV1` object

        Destroys the :class:`KywcWorkspaceV1` object.

        This request should be called either when the client does not want to
        use the workspace object any more or after the remove event to finalize
        the destruction of the object.
        """
        self._marshal(0)
        self._destroy()

    @KywcWorkspaceV1.request(
        Argument(ArgumentType.Uint),
    )
    def set_position(self, position: int) -> None:
        """Set the workspace position

        If the position is zero or less, it will be positioned at the
        beginning, if the position is the count or more, it will be positioned
        at the end.

        :param position:
            the position we want for the workspace
        :type position:
            `ArgumentType.Uint`
        """
        self._marshal(1, position)

    @KywcWorkspaceV1.request()
    def activate(self) -> None:
        """Activate the workspace

        Request that this workspace be activated.

        There is no guarantee the workspace will be actually activated, and
        behaviour may be compositor-dependentption
        """
        self._marshal(2)

    @KywcWorkspaceV1.request()
    def remove(self) -> None:
        """Remove the workspace

        Request that this workspace be removed.

        There is no guarantee the workspace will be actually removed.
        """
        self._marshal(3)


class KywcWorkspaceV1Resource(Resource):
    interface = KywcWorkspaceV1

    @KywcWorkspaceV1.event(
        Argument(ArgumentType.String),
    )
    def name(self, name: str) -> None:
        """Workspace name changed

        This event is emitted immediately after the :class:`KywcWorkspaceV1` is
        created and whenever the name of the workspace changes.

        :param name:
        :type name:
            `ArgumentType.String`
        """
        self._post_event(0, name)

    @KywcWorkspaceV1.event(
        Argument(ArgumentType.Uint),
    )
    def position(self, position: int) -> None:
        """Workspace position changed

        :param position:
        :type position:
            `ArgumentType.Uint`
        """
        self._post_event(1, position)

    @KywcWorkspaceV1.event()
    def activated(self) -> None:
        """The workspace has been activated

        The workspace will be the new "current" workspace of the system.
        """
        self._post_event(2)

    @KywcWorkspaceV1.event()
    def deactivated(self) -> None:
        """This workspace is no longer active

        surfaces that were associated only to this workspace will be hidden.
        """
        self._post_event(3)

    @KywcWorkspaceV1.event()
    def removed(self) -> None:
        """This workspace has been destroyed

        This event means the :class:`KywcWorkspaceV1` has been destroyed. It is
        guaranteed there won't be any more events for this
        :class:`KywcWorkspaceV1`. The :class:`KywcWorkspaceV1` becomes inert so
        any requests will be ignored except the destroy request.
        """
        self._post_event(4)


class KywcWorkspaceV1Global(Global):
    interface = KywcWorkspaceV1


KywcWorkspaceV1._gen_c()
KywcWorkspaceV1.proxy_class = KywcWorkspaceV1Proxy
KywcWorkspaceV1.resource_class = KywcWorkspaceV1Resource
KywcWorkspaceV1.global_class = KywcWorkspaceV1Global
