# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
# SPDX-License-Identifier: MulanPSL-2.0

from .kywc_capture_cursor_v1 import KywcCaptureCursorV1  # noqa: F401
from .kywc_capture_frame_v1 import KywcCaptureFrameV1  # noqa: F401
from .kywc_capture_manager_v1 import KywcCaptureManagerV1  # noqa: F401
