# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
# SPDX-License-Identifier: MulanPSL-2.0

from __future__ import annotations

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)


class KywcCaptureCursorV1(Interface):
    """Cursor handle

    When the seat or frame is destroyed, this object becomes inert.
    """

    name = "kywc_capture_cursor_v1"
    version = 2


class KywcCaptureCursorV1Proxy(Proxy[KywcCaptureCursorV1]):
    interface = KywcCaptureCursorV1

    @KywcCaptureCursorV1.request()
    def destroy(self) -> None:
        """Delete this object

        Destroys the object. This request can be sent at any time by the
        client.
        """
        self._marshal(0)
        self._destroy()


class KywcCaptureCursorV1Resource(Resource):
    interface = KywcCaptureCursorV1

    @KywcCaptureCursorV1.event()
    def enter(self) -> None:
        """Cursor entered a frame

        This event indicates that when a cursor enters the frame. It shall be
        generated before the "position" and "hotspot" events.

        If the pointer object referenced by the seat does not exist, this event
        will not be triggered.
        """
        self._post_event(0)

    @KywcCaptureCursorV1.event()
    def leave(self) -> None:
        """Cursor left frame

        This event indicates that when a cursor leaves the frame. No "position"
        or "hotspot" event is generated for the cursor until the cursor enters
        the frame again.

        If the pointer object referenced by the seat is removed, this event
        will be sent.
        """
        self._post_event(1)

    @KywcCaptureCursorV1.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def position(self, x: int, y: int) -> None:
        """Informs cursor position

        This event informs the cursor position. The given position is relative
        to the frame's top left corner in transformed buffer pixel coordinates.

        Note, if the frame parameter is set to null in the capture_cursor
        request, the given position coordinates are global.

        :param x:
            position x coordinates
        :type x:
            `ArgumentType.Int`
        :param y:
            position y coordinates
        :type y:
            `ArgumentType.Int`
        """
        self._post_event(2, x, y)

    @KywcCaptureCursorV1.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def hotspot(self, x: int, y: int) -> None:
        """Informs cursor hotspot

        This event informs the cursor hotspot. The hotspot describes the offset
        between the cursor image and the position of the input device.

        The parameters x and y represent the offset of the new hotspot relative
        to the origin of the cursor image, which is typically the top-left
        corner of the image.

        :param x:
            hotspot x coordinates
        :type x:
            `ArgumentType.Int`
        :param y:
            hotspot y coordinates
        :type y:
            `ArgumentType.Int`
        """
        self._post_event(3, x, y)


class KywcCaptureCursorV1Global(Global):
    interface = KywcCaptureCursorV1


KywcCaptureCursorV1._gen_c()
KywcCaptureCursorV1.proxy_class = KywcCaptureCursorV1Proxy
KywcCaptureCursorV1.resource_class = KywcCaptureCursorV1Resource
KywcCaptureCursorV1.global_class = KywcCaptureCursorV1Global
