# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
# SPDX-License-Identifier: MulanPSL-2.0

from __future__ import annotations

import enum

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)


class KywcCaptureFrameV1(Interface):
    """A frame ready for copy
    """

    name = "kywc_capture_frame_v1"
    version = 2

    class flags(enum.IntFlag):
        dmabuf = 1
        reused = 2


class KywcCaptureFrameV1Proxy(Proxy[KywcCaptureFrameV1]):
    interface = KywcCaptureFrameV1

    @KywcCaptureFrameV1.request()
    def destroy(self) -> None:
        """Delete this object, used or not

        Destroys the frame. This request can be sent at any time by the client.
        """
        self._marshal(0)
        self._destroy()

    @KywcCaptureFrameV1.request(
        Argument(ArgumentType.Uint),
    )
    def release_buffer(self, want_buffer: int) -> None:
        """Buffer is not used anymore

        Mark the buffer is not used by client. This request is sent after
        buffer event.

        :param want_buffer:
            request send buffer event when buffer is changed
        :type want_buffer:
            `ArgumentType.Uint`
        """
        self._marshal(1, want_buffer)


class KywcCaptureFrameV1Resource(Resource):
    interface = KywcCaptureFrameV1

    @KywcCaptureFrameV1.event()
    def failed(self) -> None:
        """Frame copy failed

        This event indicates that the attempted frame copy has failed. After
        receiving this event, the client should destroy the object.
        """
        self._post_event(0)

    @KywcCaptureFrameV1.event()
    def cancelled(self) -> None:
        """Frame copy has been cancelled

        Sent if the compositor cancels the frame because the source has gone.
        Upon receiving this event, the client should destroy this object.
        """
        self._post_event(1)

    @KywcCaptureFrameV1.event(
        Argument(ArgumentType.FileDescriptor),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def buffer(self, fd: int, format: int, width: int, height: int, offset: int, stride: int, modifier_hi: int, modifier_lo: int, flags: int) -> None:
        """Buffer information

        Provides information about buffer parameters that need to be used for
        this frame.

        :param fd:
            buffer file descriptor
        :type fd:
            `ArgumentType.FileDescriptor`
        :param format:
            DRM_FORMAT code
        :type format:
            `ArgumentType.Uint`
        :param width:
            buffer width in pixels
        :type width:
            `ArgumentType.Uint`
        :param height:
            buffer height in pixels
        :type height:
            `ArgumentType.Uint`
        :param offset:
            buffer offset in bytes
        :type offset:
            `ArgumentType.Uint`
        :param stride:
            buffer stride in bytes
        :type stride:
            `ArgumentType.Uint`
        :param modifier_hi:
            high 32 bits of layout modifier
        :type modifier_hi:
            `ArgumentType.Uint`
        :param modifier_lo:
            low 32 bits of layout modifier
        :type modifier_lo:
            `ArgumentType.Uint`
        :param flags:
            buffer flags
        :type flags:
            `ArgumentType.Uint`
        """
        self._post_event(2, fd, format, width, height, offset, stride, modifier_hi, modifier_lo, flags)

    @KywcCaptureFrameV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.FileDescriptor),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        version=2,
    )
    def buffer_with_plane(self, index: int, fd: int, offset: int, stride: int) -> None:
        """Buffer information with plane

        Provides information about buffer parameters with the plane index that
        need to be used for this frame.

        :param index:
            plane index
        :type index:
            `ArgumentType.Uint`
        :param fd:
            buffer file descriptor
        :type fd:
            `ArgumentType.FileDescriptor`
        :param offset:
            buffer offset in bytes
        :type offset:
            `ArgumentType.Uint`
        :param stride:
            buffer stride in bytes
        :type stride:
            `ArgumentType.Uint`
        """
        self._post_event(3, index, fd, offset, stride)

    @KywcCaptureFrameV1.event(version=2)
    def buffer_done(self) -> None:
        """All buffer parameters have been sent
        """
        self._post_event(4)


class KywcCaptureFrameV1Global(Global):
    interface = KywcCaptureFrameV1


KywcCaptureFrameV1._gen_c()
KywcCaptureFrameV1.proxy_class = KywcCaptureFrameV1Proxy
KywcCaptureFrameV1.resource_class = KywcCaptureFrameV1Resource
KywcCaptureFrameV1.global_class = KywcCaptureFrameV1Global
