# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
# SPDX-License-Identifier: MulanPSL-2.0

from __future__ import annotations

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from ..wayland import WlSeat
from .kywc_capture_cursor_v1 import KywcCaptureCursorV1
from .kywc_capture_frame_v1 import KywcCaptureFrameV1


class KywcCaptureManagerV1(Interface):
    """Manager to inform clients and begin get capturing

    This object is a manager which offers requests to start capturing from a
    source.
    """

    name = "kywc_capture_manager_v1"
    version = 2


class KywcCaptureManagerV1Proxy(Proxy[KywcCaptureManagerV1]):
    interface = KywcCaptureManagerV1

    @KywcCaptureManagerV1.request(
        Argument(ArgumentType.NewId, interface=KywcCaptureFrameV1),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.String),
    )
    def capture_output(self, overlay_cursor: int, output: str) -> Proxy[KywcCaptureFrameV1]:
        """Capture an output

        Capture the next frame of an entire output.

        :param overlay_cursor:
            composite cursor onto the frame
        :type overlay_cursor:
            `ArgumentType.Int`
        :param output:
            unique id for an output
        :type output:
            `ArgumentType.String`
        :returns:
            :class:`~pywayland.protocol.kywc_capture_v1.KywcCaptureFrameV1`
        """
        frame = self._marshal_constructor(0, KywcCaptureFrameV1, overlay_cursor, output)
        return frame

    @KywcCaptureManagerV1.request(
        Argument(ArgumentType.NewId, interface=KywcCaptureFrameV1),
        Argument(ArgumentType.String),
        Argument(ArgumentType.String),
    )
    def capture_workspace(self, workspace: str, output: str) -> Proxy[KywcCaptureFrameV1]:
        """Capture a workspace

        Capture the next frame of an entire workspace in one output.

        :param workspace:
            unique id for workspace
        :type workspace:
            `ArgumentType.String`
        :param output:
            unique id for output
        :type output:
            `ArgumentType.String`
        :returns:
            :class:`~pywayland.protocol.kywc_capture_v1.KywcCaptureFrameV1`
        """
        frame = self._marshal_constructor(1, KywcCaptureFrameV1, workspace, output)
        return frame

    @KywcCaptureManagerV1.request(
        Argument(ArgumentType.NewId, interface=KywcCaptureFrameV1),
        Argument(ArgumentType.String),
        Argument(ArgumentType.Uint),
    )
    def capture_toplevel(self, toplevel: str, without_decoration: int) -> Proxy[KywcCaptureFrameV1]:
        """Capture a toplevel

        Capture the next frame of an entire toplevel.

        :param toplevel:
            unique id for toplevel
        :type toplevel:
            `ArgumentType.String`
        :param without_decoration:
            no decoration
        :type without_decoration:
            `ArgumentType.Uint`
        :returns:
            :class:`~pywayland.protocol.kywc_capture_v1.KywcCaptureFrameV1`
        """
        frame = self._marshal_constructor(2, KywcCaptureFrameV1, toplevel, without_decoration)
        return frame

    @KywcCaptureManagerV1.request(
        Argument(ArgumentType.NewId, interface=KywcCaptureCursorV1),
        Argument(ArgumentType.Object, interface=WlSeat),
        Argument(ArgumentType.Object, interface=KywcCaptureFrameV1, nullable=True),
    )
    def capture_cursor(self, seat: WlSeat, frame: KywcCaptureFrameV1 | None) -> Proxy[KywcCaptureCursorV1]:
        """Capture a cursor

        Capture the cursor of the seat and frame.

        :param seat:
        :type seat:
            :class:`~pywayland.protocol.wayland.WlSeat`
        :param frame:
        :type frame:
            :class:`~pywayland.protocol.kywc_capture_v1.KywcCaptureFrameV1` or `None`
        :returns:
            :class:`~pywayland.protocol.kywc_capture_v1.KywcCaptureCursorV1`
        """
        cursor = self._marshal_constructor(3, KywcCaptureCursorV1, seat, frame)
        return cursor

    @KywcCaptureManagerV1.request()
    def destroy(self) -> None:
        """Destroy the manager

        All objects created by the manager will still remain valid, until their
        appropriate destroy request has been called.
        """
        self._marshal(4)
        self._destroy()


class KywcCaptureManagerV1Resource(Resource):
    interface = KywcCaptureManagerV1


class KywcCaptureManagerV1Global(Global):
    interface = KywcCaptureManagerV1


KywcCaptureManagerV1._gen_c()
KywcCaptureManagerV1.proxy_class = KywcCaptureManagerV1Proxy
KywcCaptureManagerV1.resource_class = KywcCaptureManagerV1Resource
KywcCaptureManagerV1.global_class = KywcCaptureManagerV1Global
