# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
# SPDX-License-Identifier: MulanPSL-2.0

from .kywc_output_manager_v1 import KywcOutputManagerV1  # noqa: F401
from .kywc_output_mode_v1 import KywcOutputModeV1  # noqa: F401
from .kywc_output_v1 import KywcOutputV1  # noqa: F401
