# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
# SPDX-License-Identifier: MulanPSL-2.0

from __future__ import annotations

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from .kywc_output_v1 import KywcOutputV1


class KywcOutputManagerV1(Interface):
    """Output device configuration manager

    This interface is a manager that allows reading and writing the current
    output device configuration.
    """

    name = "kywc_output_manager_v1"
    version = 1


class KywcOutputManagerV1Proxy(Proxy[KywcOutputManagerV1]):
    interface = KywcOutputManagerV1

    @KywcOutputManagerV1.request()
    def stop(self) -> None:
        """Stop sending events

        Indicates the client no longer wishes to receive events for output
        configuration changes. However the compositor may emit further events,
        until the finished event is emitted.

        The client must not send any more requests after this one.
        """
        self._marshal(0)


class KywcOutputManagerV1Resource(Resource):
    interface = KywcOutputManagerV1

    @KywcOutputManagerV1.event(
        Argument(ArgumentType.NewId, interface=KywcOutputV1),
        Argument(ArgumentType.String),
    )
    def output(self, output: KywcOutputV1, uuid: str) -> None:
        """Introduce a new output

        This event introduces a new output. This happens whenever a new output
        appears (e.g. a monitor is plugged in) or after the output manager is
        bound.

        :param output:
        :type output:
            :class:`~pywayland.protocol.kywc_output_v1.KywcOutputV1`
        :param uuid:
            Unique id of the output
        :type uuid:
            `ArgumentType.String`
        """
        self._post_event(0, output, uuid)

    @KywcOutputManagerV1.event(
        Argument(ArgumentType.Object, interface=KywcOutputV1),
    )
    def primary(self, output: KywcOutputV1) -> None:
        """Current primary output

        This events is sent when the output will become the primary output.

        :param output:
        :type output:
            :class:`~pywayland.protocol.kywc_output_v1.KywcOutputV1`
        """
        self._post_event(1, output)

    @KywcOutputManagerV1.event()
    def done(self) -> None:
        """Sent all information about current configuration

        This event is sent after all information has been sent after binding to
        the output manager object and after any subsequent changes. This
        applies to child output and mode objects as well.

        This allows changes to the output configuration to be seen as atomic,
        even if they happen via multiple events.
        """
        self._post_event(2)

    @KywcOutputManagerV1.event()
    def finished(self) -> None:
        """The compositor has finished with the manager

        This event indicates that the compositor is done sending manager
        events. The compositor will destroy the object immediately after
        sending this event, so it will become invalid and the client should
        release any resources associated with it.
        """
        self._post_event(3)


class KywcOutputManagerV1Global(Global):
    interface = KywcOutputManagerV1


KywcOutputManagerV1._gen_c()
KywcOutputManagerV1.proxy_class = KywcOutputManagerV1Proxy
KywcOutputManagerV1.resource_class = KywcOutputManagerV1Resource
KywcOutputManagerV1.global_class = KywcOutputManagerV1Global
