# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
# SPDX-License-Identifier: MulanPSL-2.0

from __future__ import annotations

import enum

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from .kywc_output_mode_v1 import KywcOutputModeV1


class KywcOutputV1(Interface):
    """Output device

    A output has some read-only properties: modes, name, description,
    physical_size. These cannot be changed by clients.

    Properties sent via this interface are applied atomically via the
    kywc_output_manager.done event. No guarantees are made regarding the order
    in which properties are sent.
    """

    name = "kywc_output_v1"
    version = 1

    class capability(enum.IntFlag):
        power = 1
        brightness = 2
        color_temp = 4


class KywcOutputV1Proxy(Proxy[KywcOutputV1]):
    interface = KywcOutputV1

    @KywcOutputV1.request()
    def destroy(self) -> None:
        """Destroy the output object

        This request indicates that the client will no longer use this output
        object.
        """
        self._marshal(0)
        self._destroy()


class KywcOutputV1Resource(Resource):
    interface = KywcOutputV1

    @KywcOutputV1.event(
        Argument(ArgumentType.String),
    )
    def name(self, name: str) -> None:
        """Output name

        This event describes the output name.

        The name event is sent after a kywc_output object is created. This
        event is only sent once per object, and the name does not change over
        the lifetime of the kywc_output object.

        :param name:
        :type name:
            `ArgumentType.String`
        """
        self._post_event(0, name)

    @KywcOutputV1.event(
        Argument(ArgumentType.String),
    )
    def make(self, make: str) -> None:
        """Output monitor manufacturer

        This event describes the manufacturer of the output monitor.

        :param make:
        :type make:
            `ArgumentType.String`
        """
        self._post_event(1, make)

    @KywcOutputV1.event(
        Argument(ArgumentType.String),
    )
    def model(self, model: str) -> None:
        """Output monitor model

        This event describes the model of the output monitor.

        :param model:
        :type model:
            `ArgumentType.String`
        """
        self._post_event(2, model)

    @KywcOutputV1.event(
        Argument(ArgumentType.String),
    )
    def serial_number(self, serial_number: str) -> None:
        """Output serial number

        This event describes the serial number of the output monitor.

        :param serial_number:
        :type serial_number:
            `ArgumentType.String`
        """
        self._post_event(3, serial_number)

    @KywcOutputV1.event(
        Argument(ArgumentType.String),
    )
    def description(self, description: str) -> None:
        """Output description

        This event describes a human-readable description of the output.

        :param description:
        :type description:
            `ArgumentType.String`
        """
        self._post_event(4, description)

    @KywcOutputV1.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def physical_size(self, width: int, height: int) -> None:
        """Output monitor physical size

        This event describes the physical size of the monitor. This event is
        only sent if has a physical size (e.g. is not a projector or a virtual
        device).

        :param width:
            width in millimeters of the output
        :type width:
            `ArgumentType.Int`
        :param height:
            height in millimeters of the output
        :type height:
            `ArgumentType.Int`
        """
        self._post_event(5, width, height)

    @KywcOutputV1.event(
        Argument(ArgumentType.NewId, interface=KywcOutputModeV1),
    )
    def mode(self, mode: KywcOutputModeV1) -> None:
        """Introduce a mode

        This event introduces a mode for this monitor. It is sent once per
        supported mode.

        :param mode:
        :type mode:
            :class:`~pywayland.protocol.kywc_output_v1.KywcOutputModeV1`
        """
        self._post_event(6, mode)

    @KywcOutputV1.event(
        Argument(ArgumentType.Uint),
    )
    def capabilities(self, flags: int) -> None:
        """Capability flags

        What capabilities this output has, sent on startup before the first
        done event.

        :param flags:
        :type flags:
            `ArgumentType.Uint`
        """
        self._post_event(7, flags)

    @KywcOutputV1.event(
        Argument(ArgumentType.Int),
    )
    def enabled(self, enabled: int) -> None:
        """The output is enabled or disabled

        This event describes whether the output is enabled. A disabled output
        is not mapped to a region of the global compositor space.

        When a output is disabled, some properties (current_mode, position,
        transform and scale) are irrelevant.

        :param enabled:
            zero if disabled, non-zero if enabled
        :type enabled:
            `ArgumentType.Int`
        """
        self._post_event(8, enabled)

    @KywcOutputV1.event(
        Argument(ArgumentType.Object, interface=KywcOutputModeV1),
    )
    def current_mode(self, mode: KywcOutputModeV1) -> None:
        """Current mode

        This event describes the mode currently in use for this output. It is
        only sent if the output is enabled.

        :param mode:
        :type mode:
            :class:`~pywayland.protocol.kywc_output_v1.KywcOutputModeV1`
        """
        self._post_event(9, mode)

    @KywcOutputV1.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def position(self, x: int, y: int) -> None:
        """Current position

        This events describes the position of the output in the global
        compositor space. It is only sent if the output is enabled.

        :param x:
            x position within the global compositor space
        :type x:
            `ArgumentType.Int`
        :param y:
            y position within the global compositor space
        :type y:
            `ArgumentType.Int`
        """
        self._post_event(10, x, y)

    @KywcOutputV1.event(
        Argument(ArgumentType.Int),
    )
    def transform(self, transform: int) -> None:
        """Current transformation

        This event describes the transformation currently applied to the
        output. It is only sent if the output is enabled.

        :param transform:
        :type transform:
            `ArgumentType.Int`
        """
        self._post_event(11, transform)

    @KywcOutputV1.event(
        Argument(ArgumentType.Fixed),
    )
    def scale(self, scale: float) -> None:
        """Current scale

        This events describes the scale of the output in the global compositor
        space. It is only sent if the output is enabled.

        :param scale:
        :type scale:
            `ArgumentType.Fixed`
        """
        self._post_event(12, scale)

    @KywcOutputV1.event(
        Argument(ArgumentType.Uint),
    )
    def power(self, power: int) -> None:
        """Current power state

        This events describes the power(dpms) state.

        :param power:
        :type power:
            `ArgumentType.Uint`
        """
        self._post_event(13, power)

    @KywcOutputV1.event(
        Argument(ArgumentType.Uint),
    )
    def brightness(self, brightness: int) -> None:
        """Current output brightness

        This events describes the output brightness.

        :param brightness:
        :type brightness:
            `ArgumentType.Uint`
        """
        self._post_event(14, brightness)

    @KywcOutputV1.event(
        Argument(ArgumentType.Uint),
    )
    def color_temp(self, color_temp: int) -> None:
        """Current color temperature

        This events describes the output color temperature.

        :param color_temp:
        :type color_temp:
            `ArgumentType.Uint`
        """
        self._post_event(15, color_temp)

    @KywcOutputV1.event()
    def finished(self) -> None:
        """The output has disappeared

        This event indicates that the output is no longer available. The output
        object becomes inert. Clients should send a destroy request and release
        any resources associated with it.
        """
        self._post_event(16)


class KywcOutputV1Global(Global):
    interface = KywcOutputV1


KywcOutputV1._gen_c()
KywcOutputV1.proxy_class = KywcOutputV1Proxy
KywcOutputV1.resource_class = KywcOutputV1Resource
KywcOutputV1.global_class = KywcOutputV1Global
