# This file has been autogenerated by the pywayland scanner

# SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
# SPDX-License-Identifier: MulanPSL-2.0

from __future__ import annotations

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)


class KywcOutputModeV1(Interface):
    """Output mode

    This object describes an output mode.

    Properties sent via this interface are applied atomically via the
    kywc_output_manager.done event. No guarantees are made regarding the order
    in which properties are sent.
    """

    name = "kywc_output_mode_v1"
    version = 1


class KywcOutputModeV1Proxy(Proxy[KywcOutputModeV1]):
    interface = KywcOutputModeV1

    @KywcOutputModeV1.request()
    def destroy(self) -> None:
        """Destroy the mode object

        This request indicates that the client will no longer use this mode
        object.
        """
        self._marshal(0)
        self._destroy()


class KywcOutputModeV1Resource(Resource):
    interface = KywcOutputModeV1

    @KywcOutputModeV1.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def size(self, width: int, height: int) -> None:
        """Mode size

        This event describes the mode size. The size is given in physical
        hardware units of the output device. This is not necessarily the same
        as the output size in the global compositor space. For instance, the
        output may be scaled or transformed.

        :param width:
            width of the mode in hardware units
        :type width:
            `ArgumentType.Int`
        :param height:
            height of the mode in hardware units
        :type height:
            `ArgumentType.Int`
        """
        self._post_event(0, width, height)

    @KywcOutputModeV1.event(
        Argument(ArgumentType.Int),
    )
    def refresh(self, refresh: int) -> None:
        """Mode refresh rate

        This event describes the mode's fixed vertical refresh rate. It is only
        sent if the mode has a fixed refresh rate.

        :param refresh:
            vertical refresh rate in mHz
        :type refresh:
            `ArgumentType.Int`
        """
        self._post_event(1, refresh)

    @KywcOutputModeV1.event()
    def preferred(self) -> None:
        """Mode is preferred

        This event advertises this mode as preferred.
        """
        self._post_event(2)

    @KywcOutputModeV1.event()
    def finished(self) -> None:
        """The mode has disappeared

        This event indicates that the mode is no longer available. The mode
        object becomes inert. Clients should send a destroy request and release
        any resources associated with it.
        """
        self._post_event(3)


class KywcOutputModeV1Global(Global):
    interface = KywcOutputModeV1


KywcOutputModeV1._gen_c()
KywcOutputModeV1.proxy_class = KywcOutputModeV1Proxy
KywcOutputModeV1.resource_class = KywcOutputModeV1Resource
KywcOutputModeV1.global_class = KywcOutputModeV1Global
