# Copyright (C) 2026 CharOfString <markus_verify@126.com>
#
# This file is part of gxde-dock.
#
# gxde-dock is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# gxde-dock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with gxde-dock.  If not, see <https://www.gnu.org/licenses/>.

"""
Since X11 support has been dropped for this is a Wayland service, there is no need to translate
xutils.go to Python 3. Instead, this is a replacement for it that supports gxde-wlcom.

Window management via kywc_toplevel_v1 protocol, currently only supports gxde-wlcom in GXDE OS.

The protocol may be found in  protocols folder. It is auto-generated by rescan_protocols.sh.
Please don't run that script in CI/CD pipelines for:
    1. It is interactive. It do ask you to give the directory of the protocol XML files.
    2. It requires you to have a copy of source code of gxde-wlcom.

If you want to update the protocols, manually run rescan_protocols.sh in locally, then do a
git push, and you should be good to go.
"""

import mmap
import os
import logging
from dataclasses import dataclass, field
from pywayland.client import Display

from .protocols.kywc_toplevel_v1 import KywcToplevelManagerV1, KywcToplevelV1
from .protocols.kywc_capture_v1 import KywcCaptureManagerV1

log = logging.getLogger("dock.TopLevel")

@dataclass
class ToplevelInfo:
    uuid: str = ""
    title: str = ""
    app_id: str = ""
    pid: int = 0
    state: int = 0    # maximized=1, minimized=2, activated=4, fullscreen=8
    geometry: tuple = (0, 0, 0, 0)    # (x, y, w, h)

    @property
    def is_active(self):
        return bool(self.state & 4)

    @property
    def is_minimized(self):
        return bool(self.state & 2)


_display = None
_registry = None
_manager = None
_capture_manager = None
_toplevels = {}    # uuid (str) -> (ToplevelInfo, KywcToplevelV1 proxy)
_callbacks = {
    "created": None,
    "updated": None,
    "closed": None,
}
_pending_toplevels = []  # 回调注册前收到的窗口，注册后回放


def on_toplevel_created(cb):
    """注册回调: cb(ToplevelInfo)。已缓存的窗口立即回放。"""
    _callbacks["created"] = cb
    for info in _pending_toplevels:
        cb(info)
    _pending_toplevels.clear()

def _update_info(uuid, field, value):
    """When a toplevel is updated..."""
    entry = _toplevels.get(uuid)
    if not entry:
        return
    info, _ = entry
    setattr(info, field, value)

    cb = _callbacks.get("updated")
    if cb:
        cb(info)

def _on_closed(uuid):
    """When a toplevel is closed..."""
    entry = _toplevels.pop(uuid, None)
    if not entry:
        return
    info, _ = entry
    cb = _callbacks.get("closed")
    if cb:
        cb(uuid)
    log.debug(f"Toplevel {uuid} closed")

def _on_toplevel(toplevel_manager, toplevel_proxy, uuid):
    """New window: store info and notify daemon"""
    info = ToplevelInfo(uuid=uuid)
    _toplevels[uuid] = (info, toplevel_proxy)

    disp = toplevel_proxy.dispatcher
    disp["title"] = lambda tl, v: _update_info(uuid, "title", v)
    disp["app_id"] = lambda tl, v: _update_info(uuid, "app_id", v)
    disp["pid"] = lambda tl, v: _update_info(uuid, "pid", v)
    disp["state"] = lambda tl, v: _update_info(uuid, "state", v)
    disp["geometry"] = lambda tl, x, y, w, h: _update_info(uuid, "geometry", (x, y, w, h))
    disp["closed"] = lambda tl: _on_closed(uuid)
    disp["done"] = lambda tl: None

    cb = _callbacks.get("created")
    if cb:
        cb(info)
    else:
        _pending_toplevels.append(info)

    log.debug(f"Toplevel {uuid}: app_id={info.app_id} pid={info.pid}")

def _on_global(reg, name, interface, version):
    global _capture_manager
    if interface == KywcToplevelManagerV1.name:
        global _manager
        protocol_ver = min(version, KywcToplevelManagerV1.version)
        _manager = reg.bind(name, KywcToplevelManagerV1, protocol_ver)
        _manager.dispatcher["toplevel"] = _on_toplevel
        log.info(f"Bound protocol {interface} v.{protocol_ver}.")
    elif interface == KywcCaptureManagerV1.name:
        protocol_ver = min(version, KywcCaptureManagerV1.version)
        _capture_manager = reg.bind(name, KywcCaptureManagerV1, protocol_ver)
        log.info(f"Bound protocol {interface} v.{protocol_ver}.")
    else:
        log.debug(f"Protocol {interface} v.{version} is unknown to this WM.")

def on_toplevel_updated(cb):
    """Callback registration: cb(ToplevelInfo)"""
    _callbacks["updated"] = cb

def on_toplevel_closed(cb):
    """Callback registration: cb(uuid: str)"""
    _callbacks["closed"] = cb

def is_wayland():
    return bool(os.environ.get("WAYLAND_DISPLAY"))

def init_display():
    global _display, _registry, _manager
    if _display:
        return
    if not is_wayland():
        raise RuntimeError("WAYLAND_DISPLAY NOT set!!")

    _display = Display()
    _display.connect()
    _registry = _display.get_registry()
    _registry.dispatcher["global"] = _on_global
    _display.roundtrip()
    _display.roundtrip()

    if _manager is None:
        log.warning("kywc_toplevel_manager_v1 NOT available!!")
    log.info("Wayland display OK.")

def get_fd():
    return _display.get_fd() if _display else -1


def dispatch(block=False):
    if _display:
        _display.dispatch(block=block)

# Window ops
def _get_proxy(uuid):
    entry = _toplevels.get(uuid)
    return entry[1] if entry else None

def activate_window(uuid):
    p = _get_proxy(uuid)
    if p:
        p.activate()
        _display.flush()

def close_window(uuid, timestamp=0):
    p = _get_proxy(uuid)
    if p:
        p.close()
        _display.flush()

def minimize_window(uuid):
    p = _get_proxy(uuid)
    if p:
        p.set_minimized()
        _display.flush()

def maximize_window(uuid):
    p = _get_proxy(uuid)
    if p:
        p.set_maximized(None)
        _display.flush()

def make_window_above(uuid):
    pass

def move_window(uuid):
    p = _get_proxy(uuid)
    if p:
        p.set_position(0, 0)
        _display.flush()

def get_toplevel_info(uuid):
    entry = _toplevels.get(uuid)
    return entry[0] if entry else None

def list_toplevels():
    return list(_toplevels.keys())


def capture_toplevel(uuid):
    """Return (pixels, format, width, height, stride) for a Wayland toplevel.

    gxde-wlcom's protocol returns immutable DMA-BUF ID. Buffers are ARGB8888 &
    XRGB8888, you may copy them before they are released.
    """
    if not _display or not _capture_manager or uuid not in _toplevels:
        return b"", 0, 0, 0, 0

    result = {}
    frame = _capture_manager.capture_toplevel(uuid, 1)

    def on_buffer(unused_frame, fd, pixel_format, width, height, offset,
                  stride, modifier_hi, modifier_lo, flags):
        result["buffer_received"] = True
        modifier = (modifier_hi << 32) | modifier_lo
        # DRM_FORMAT_MOD_LINEAR is 0
        # We also have DRM_FORMAT_MOD_INVALID
        if modifier not in (0, 0x00FFFFFFFFFFFFFF):
            os.close(fd)
            return

        length = offset + stride * height
        try:
            mapping = mmap.mmap(fd, length, access=mmap.ACCESS_READ)
            result["value"] = (
                bytes(mapping[offset:offset + stride * height]),
                pixel_format, width, height, stride)
            mapping.close()
        except (OSError, ValueError) as error:
            log.warning(f"Failed to map capture buffer for {uuid}: {error}")
        finally:
            os.close(fd)

    frame.dispatcher["buffer"] = on_buffer
    frame.dispatcher["failed"] = lambda unused_frame: result.setdefault(
        "value", (b"", 0, 0, 0, 0))
    frame.dispatcher["cancelled"] = lambda unused_frame: result.setdefault(
        "value", (b"", 0, 0, 0, 0))

    try:
        _display.roundtrip()
    except Exception as error:
        log.warning(f"Failed to capture Wayland toplevel {uuid}: {error}")
    finally:
        if result.get("buffer_received"):
            frame.release_buffer(0)
        frame.destroy()

    return result.get("value", (b"", 0, 0, 0, 0))
